name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build C# Project
        run: |
          cd src/Mirance
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release -r win-x64 -o ./publish
      
      - name: Create debug.bat
        run: |
          cd src/Mirance/publish
          echo @echo off > debug.bat
          echo Mirance.exe > debug.bat
          echo pause >> debug.bat
      
      - name: Upload all files
        uses: actions/upload-artifact@v4
        with:
          name: Mirance-win-x64
          path: src/Mirance/publish/*
